# Generated by Django 5.2 on 2025-04-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_id', models.CharField(max_length=50, null=True, unique=True)),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=100, null=True)),
                ('machine_make', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('hours', models.FloatField(null=True)),
                ('shift', models.CharField(max_length=20, null=True)),
                ('causes_of_breakdown', models.TextField(null=True)),
                ('technician_attend', models.CharField(max_length=100, null=True)),
                ('operator_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='current_stock_data_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=50, null=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='current_stock_data_master',
            fields=[
                ('spare_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('minimum_stock_quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='inward_masters',
            fields=[
                ('inward_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=40, null=True, unique=True)),
                ('invoice_id', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=40, null=True)),
                ('vendor_phone', models.IntegerField(null=True)),
                ('vendor_gst', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='machine_details',
            fields=[
                ('machine_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=50, null=True)),
                ('machine_make', models.CharField(max_length=50, null=True)),
                ('machine_model', models.CharField(max_length=50, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('specification1', models.CharField(max_length=50, null=True)),
                ('specification2', models.CharField(max_length=50, null=True)),
                ('specification3', models.CharField(max_length=50, null=True)),
                ('specification4', models.CharField(max_length=50, null=True)),
                ('specification5', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='minimum_stock_quantity_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=100, null=True)),
                ('machine_make', models.CharField(max_length=100, null=True)),
                ('spare_id', models.CharField(max_length=40, null=True, unique=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('spare_importance', models.CharField(max_length=50, null=True)),
                ('quantities_used', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='minimum_stock_quantity_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=40, null=True, unique=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('quantities_used', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='minimum_stocks_quantity_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=100, null=True)),
                ('machine_make', models.CharField(max_length=100, null=True)),
                ('spare_id', models.CharField(max_length=40, null=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('spare_importance', models.CharField(max_length=50, null=True)),
                ('quantities_used', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='minimum_stocks_quantity_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=40, null=True, unique=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('quantities_used', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outward_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outward_id', models.CharField(max_length=50, null=True)),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=40, null=True)),
                ('spare_id', models.CharField(max_length=40, null=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('purpose', models.CharField(max_length=50, null=True)),
                ('out_quantity', models.IntegerField(null=True)),
                ('minimum_stock_quantity', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='spare_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=40, null=True, unique=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('spare_make', models.CharField(max_length=30, null=True)),
                ('specification_I', models.CharField(max_length=50, null=True)),
                ('specification_II', models.CharField(max_length=50, null=True)),
                ('specification_III', models.CharField(max_length=50, null=True)),
                ('specification_IV', models.CharField(max_length=50, null=True)),
                ('minimum_stock_quantity', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='spares_add_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=40, null=True)),
                ('machine_name', models.CharField(max_length=50, null=True)),
                ('machine_make', models.CharField(max_length=50, null=True)),
                ('machine_model', models.CharField(max_length=50, null=True)),
                ('spare_id', models.CharField(max_length=40, null=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('spare_importance', models.CharField(max_length=50, null=True)),
                ('quantities_used', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=50, null=True)),
                ('spare_name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sparesapp.breakdownmaster')),
            ],
        ),
        migrations.CreateModel(
            name='inward_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=40, null=True, unique=True)),
                ('invoice_id', models.CharField(max_length=50, null=True)),
                ('spare_id', models.CharField(max_length=40, null=True)),
                ('spare_name', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=40, null=True)),
                ('vendor_phone', models.IntegerField(null=True)),
                ('vendor_gst', models.FloatField(null=True)),
                ('invoice_cost', models.FloatField(null=True)),
                ('invoice_quantity', models.IntegerField(null=True)),
                ('cost_per_quantity', models.FloatField(null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('inward_id', models.ForeignKey(db_column='inward_id', on_delete=django.db.models.deletion.CASCADE, to='sparesapp.inward_masters')),
            ],
        ),
    ]
