# Generated by Django 5.2 on 2025-04-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward_details',
            name='inward_id',
        ),
        migrations.AddField(
            model_name='inward_details',
            name='inward',
            field=models.ForeignKey(default='oooo', on_delete=django.db.models.deletion.CASCADE, to='sparesapp.inward_masters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='batch_id',
            field=models.CharField(default='oooo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='cost_per_quantity',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='invoice_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='invoice_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='invoice_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='spare_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='spare_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='vendor_gst',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='vendor_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='batch_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='invoice_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='inward_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='vendor_gst',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inward_masters',
            name='vendor_phone',
            field=models.CharField(max_length=15),
        ),
    ]
