# Generated by Django 5.2 on 2025-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0002_remove_inward_details_inward_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward_details',
            name='date',
        ),
        migrations.AddField(
            model_name='inward_masters',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
