# Generated by Django 5.2 on 2025-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0003_remove_inward_details_date_inward_masters_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimum_stocks_quantity_master',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
