# Generated by Django 5.2 on 2025-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0004_alter_minimum_stocks_quantity_master_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimum_stocks_quantity_master',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
