# Generated by Django 5.2 on 2025-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0005_minimum_stocks_quantity_master_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_stock_data_master',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
