# Generated by Django 5.2 on 2025-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0006_current_stock_data_master_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_stock_data_master',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
    ]
