# Generated by Django 5.2 on 2025-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0007_current_stock_data_master_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward_masters',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inward_masters',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inward_details',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
