# Generated by Django 5.2 on 2025-04-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0008_inward_masters_grand_total_inward_masters_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_stock_data_master',
            name='minimum_stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outward_details',
            name='minimum_stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spare_details',
            name='minimum_stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
