# Generated by Django 5.2 on 2025-04-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0009_alter_current_stock_data_master_minimum_stock_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreakdownDetail',
        ),
        migrations.DeleteModel(
            name='BreakdownMaster',
        ),
    ]
