# Generated by Django 5.2 on 2025-04-24 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0010_delete_breakdowndetail_delete_breakdownmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownMaster',
            fields=[
                ('breakdown_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=100, null=True)),
                ('machine_make', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('hours', models.FloatField(null=True)),
                ('shift', models.CharField(max_length=20, null=True)),
                ('causes_of_breakdown', models.TextField(null=True)),
                ('technician_attend', models.CharField(max_length=100, null=True)),
                ('operator_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_id', models.CharField(max_length=50, null=True)),
                ('spare_name', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('breakdown_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparesapp.breakdownmaster')),
            ],
        ),
    ]
