# Generated by Django 5.2 on 2025-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0011_breakdownmaster_breakdowndetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_stock_data_details',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
