# Generated by Django 5.2 on 2025-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0012_alter_current_stock_data_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdowndetail',
            name='machine_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
