# Generated by Django 5.2 on 2025-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0013_breakdowndetail_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward_details',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
