# Generated by Django 5.2 on 2025-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0014_inward_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdowndetail',
            name='causes_of_breakdown',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='breakdowndetail',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='breakdowndetail',
            name='machine_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
