# Generated by Django 5.2 on 2025-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0015_breakdowndetail_causes_of_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preventive_work',
            fields=[
                ('preventive_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('type_of_work', models.CharField(max_length=50, null=True)),
                ('type_of_work_mode', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
