# Generated by Django 5.2 on 2025-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0016_preventive_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive_work',
            old_name='type_of_work_mode',
            new_name='machine_name',
        ),
        migrations.AddField(
            model_name='preventive_work',
            name='work_cycle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
