# Generated by Django 5.2 on 2025-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0017_rename_type_of_work_mode_preventive_work_machine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventive_work',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
