# Generated by Django 5.2 on 2025-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0018_alter_preventive_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='preventive_work_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventive_id', models.CharField(max_length=50)),
                ('machine_id', models.CharField(max_length=50, null=True)),
                ('machine_name', models.CharField(max_length=50, null=True)),
                ('type_of_work', models.CharField(max_length=50, null=True)),
                ('work_cycle', models.CharField(max_length=50, null=True)),
                ('checked_by', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
