# Generated by Django 5.2 on 2025-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0019_preventive_work_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='breakdowndetail',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='breakdowndetail',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdownmaster',
            name='Breakdown_Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breakdownmaster',
            name='damage_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
