# Generated by Django 5.2 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0020_userimage_breakdowndetail_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
