# Generated by Django 5.2 on 2025-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparesapp', '0021_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
